# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region                      = "ap-southeast-1"
  access_key                  = "dummy"
  secret_key                  = "dummy"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
}
